CREATE TABLE hello
(
    ID CHAR(5) CONSTRAINT PK_HELLO_ID PRIMARY KEY,
    NAME VARCHAR2(20),
    TEL VARCHAR2(20),
    AGE NUMBER(3)
);

INSERT INTO "SOLUSER"."HELLO" (ID, NAME, TEL, AGE)
VALUES ('12345', '홍길동', '010-1234-1234', '30');

INSERT INTO "SOLUSER"."PHONEBOOK" 
(PHONEID, NAME, PHONENO, TELNO, POSTADDRESS, ADDRESS, POSTNO, EMAIL, GROUPID, MEMO)
VALUES ('호동이', '강호동', '010-3333-4444', NULL, '서울시', '강남구 청담동', '33333', 'HODONG@NAVER.COM',
'2', '친한 친구');

INSERT INTO "SOLUSER"."PHONEBOOK" 
(PHONEID, NAME, PHONENO, TELNO, POSTADDRESS, ADDRESS, POSTNO, EMAIL, GROUPID, MEMO)
VALUES ('종국이', '김종국', '010-3333-3333', NULL, '안양시', '안양구 안양동', '2222', 'JONGKOOK@NAVER.COM',
'2', '친한 친구');

INSERT INTO "SOLUSER"."PHONEBOOK" 
(PHONEID, NAME, PHONENO, TELNO, POSTADDRESS, ADDRESS, POSTNO, EMAIL, GROUPID, MEMO)
VALUES ('동석이', '마동석', '010-5555-5555', NULL, '서울시', '종로구 평창동', '2323', 'DONGSEOK@NAVER.COM',
'2', '친한 친구');

INSERT INTO "SOLUSER"."PHONEBOOK" 
(PHONEID, NAME, PHONENO, TELNO, POSTADDRESS, ADDRESS, POSTNO, EMAIL, GROUPID, MEMO)
VALUES ('여직원', '가민지', '010-1234-1212', NULL, '성남시', '분당구 분당동', '5151', 'MINJI@GMAIL.COM',
'3', '직장동료');

INSERT INTO "SOLUSER"."PHONEBOOK" 
(PHONEID, NAME, PHONENO, TELNO, POSTADDRESS, ADDRESS, POSTNO, EMAIL, GROUPID, MEMO)
VALUES ('남직원', '권철주', '010-7777-1000', NULL, '이천시', '이천구 이천동', '1222', 'IRONZOO@GMAIL.COM',
'3', '직장동료');

INSERT INTO "SOLUSER"."PHONEBOOK" 
(PHONEID, NAME, PHONENO, TELNO, POSTADDRESS, ADDRESS, POSTNO, EMAIL, GROUPID, MEMO)
VALUES ('팀장님', '윤성혁', '010-1004-1004', NULL, '성남시', '수정구 수정동', '5152', 'SHYOON@GMAIL.COM',
'3', '직장동료');

INSERT INTO "SOLUSER"."PHONEBOOK" 
(PHONEID, NAME, PHONENO, TELNO, POSTADDRESS, ADDRESS, POSTNO, EMAIL, GROUPID, MEMO)
VALUES ('MOTHER', '엄마', '010-1111-1111', '032-111-1111', '용인시', '처인구 유림동', '12345', 'MOTHER@NAVER.COM',
'1', '사랑하는 가족');

INSERT INTO "SOLUSER"."PHONEBOOK" 
(PHONEID, NAME, PHONENO, TELNO, POSTADDRESS, ADDRESS, POSTNO, EMAIL, GROUPID, MEMO)
VALUES ('FATHER', '아빠', '010-2222-2222', '032-111-1111', '용인시', '처인구 유림동', '12345', 'FATHER@NAVER.COM',
'1', '사랑하는 가족');

SELECT a.name, a.phoneno, a.address, a.postno, a.groupid, b.groupid, b.groupsign
    FROM phonebook a, phonegroup b
    WHERE a.groupid = b.groupid
    ORDER BY A.GROUPID;