-- 함수(function) 호출

SELECT '7900' AS EMPNO, FUNC_EMP_NAME_IN_RETURN(7900) FROM DUAL;
SELECT '7566' AS EMPNO, FUNC_EMP_NAME_IN_RETURN(7566) FROM DUAL;

SELECT EMPNO, ENAME, FUNC_EMP_NAME_IN_RETURN(EMPNO) FROM EMP;