-- 저장 프로시저(Stored Procedure)
-- 이름을 가진 PL/SQL 이다
-- 호출 : PL/SQL에서 호출

SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE PROC_EMP_PARAMETER_IN(V_EMPNO IN NUMBER)
IS
    V_ENAME VARCHAR2(10);
BEGIN
    V_ENAME := 'EZEN';
    
    DBMS_OUTPUT.PUT_LINE('EMPNO : ' || V_EMPNO);
    DBMS_OUTPUT.PUT_LINE('EMPNO : ' || V_ENAME);
END;