-- 함수(function) 호출

DECLARE
    V_ENAME EMP.ENAME%TYPE; -- 결과값
BEGIN
    V_ENAME := FUNC_EMP_NAME_IN_RETURN(7900);
    DBMS_OUTPUT.PUT_LINE('ENAME : ' || 7900);
    DBMS_OUTPUT.PUT_LINE('ENAME : ' || V_ENAME);
    
    V_ENAME := FUNC_EMP_NAME_IN_RETURN(7566);
    DBMS_OUTPUT.PUT_LINE('ENAME : ' || 7566);
    DBMS_OUTPUT.PUT_LINE('ENAME : ' || V_ENAME);
    
END;
/