-- 그룹함수: 다중행 함수
-- 데이터의 합
-- SUM(COLUMN)

-- 전체 사원의 급여 총액
SELECT SUM(SAL) FROM EMP;

SELECT SUM(SAL) FROM EMP WHERE DEPTNO = 10;
SELECT SUM(SAL) FROM EMP WHERE DEPTNO = 20;
SELECT SUM(SAL) FROM EMP WHERE DEPTNO = 30;

SELECT '10' AS DEPT, COUNT(SAL), SUM(SAL), TRUNC(AVG(SAL),1) FROM EMP WHERE DEPTNO = 10
UNION ALL --10번 부서에, 3명이 있고, 급여총액, 평균급여
SELECT '20' AS DEPT, COUNT(SAL), SUM(SAL), TRUNC(AVG(SAL),1) FROM EMP WHERE DEPTNO = 20
UNION ALL --20번 부서에, 3명이 있고, 급여총액, 평균급여
SELECT '30' AS DEPT, COUNT(SAL), SUM(SAL), TRUNC(AVG(SAL),1) FROM EMP WHERE DEPTNO = 30;
          --30번 부서에, 3명이 있고, 급여총액, 평균급여