-- 그룹함수 : count, avg, min, max, sum
-- 그룹함수를 통해서 나온 결과를 묶어서 처리
-- GROUP BY

-- 부서별 사원들의 평균 급여
SELECT '10' AS DEMPNO, TRUNC(AVG(SAL)) FROM EMP WHERE DEPTNO = 10
UNION ALL
SELECT '20' AS DEMPNO, TRUNC(AVG(SAL)) FROM EMP WHERE DEPTNO = 20
UNION ALL
SELECT '30' AS DEMPNO, TRUNC(AVG(SAL)) FROM EMP WHERE DEPTNO = 30
UNION ALL
SELECT '40' AS DEMPNO, TRUNC(AVG(SAL)) FROM EMP WHERE DEPTNO = 40;

-- GROUP BY
-- 그룹화할 칼럼을 지정
-- 여러 칼럼을 지정 가능

--부서별 사원들의 평균 급여액
SELECT DEPTNO, TRUNC(AVG(SAL)) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO;

--부서별, 직책별 평균 급여액
SELECT DEPTNO, JOB, SAL FROM EMP ORDER BY DEPTNO;
SELECT DEPTNO, JOB, TRUNC(AVG(SAL)) FROM EMP GROUP BY DEPTNO, JOB ORDER BY DEPTNO;

-- 부서별 총 급여액
SELECT DEPTNO, SUM(SAL) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO;
-- 부서별, 직책별 총 급여액
-- SELECT DEPTNO, JOB, SUM(SAL) FROM EMP ORDER BY DEPTNO; 단일행, 그룹행을 결합해서 기술할 수 없다
SELECT DEPTNO, JOB, SUM(SAL) FROM EMP GROUP BY DEPTNO, JOB ORDER BY DEPTNO;

--[문제]
-- 부서별 사원들의 총수
SELECT DEPTNO, COUNT(DEPTNO) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO;
--부서별 사원들의 총수, 급여총액, 평균급여액
SELECT DEPTNO, COUNT(DEPTNO), SUM(SAL), TRUNC(AVG(SAL)) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO;
--부서별 사원들의 급여총액, 평균급여액, 최고급여액, 최저급여액
SELECT DEPTNO, SUM(SAL), TRUNC(AVG(SAL)), MAX(SAL), MIN(SAL) FROM EMP GROUP BY DEPTNO ORDER BY DEPTNO;