-- 자료형 변환 : 날짜나 숫자를 문자로 변환
-- TO_CHAR(데이터, 포맷)

--날짜를 스트링 포맷으로 지정(년월일)
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY.MM.DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD') FROM DUAL;
SELECT TO_CHAR(SYSDATE, 'YY/MM/DD') FROM DUAL;

-- 세기(CC) : 21세기
SELECT TO_CHAR(SYSDATE, 'CC')FROM DUAL;
-- 연도
SELECT TO_CHAR(SYSDATE, 'YY') FROM DUAL; --2자리
SELECT TO_CHAR(SYSDATE, 'YYYY') FROM DUAL; --4자리
-- 월
SELECT TO_CHAR(SYSDATE, 'MM') FROM DUAL; -- 2자리
SELECT TO_CHAR(SYSDATE, 'MON') FROM DUAL; -- 2자리 + 월(언어별 월이름약자)
SELECT TO_CHAR(SYSDATE, 'MONTH') FROM DUAL; -- 2자리 + 월(언어별 월이름전체)
-- 일
SELECT TO_CHAR(SYSDATE, 'DD') FROM DUAL; --2자리(2자리 숫자)
SELECT TO_CHAR(SYSDATE, 'DDD') FROM DUAL; --3자리(1년중에 몇번째날, 1~366)
--요일
SELECT TO_CHAR(SYSDATE, 'DY') FROM DUAL; -- 언어별 요일 약자
SELECT TO_CHAR(SYSDATE, 'DAY') FROM DUAL; -- 언어별 요일 전체
SELECT TO_CHAR(SYSDATE, 'W') FROM DUAL; -- 월의 몇번째 주, 1~5
SELECT TO_CHAR(SYSDATE, 'WW') FROM DUAL; -- 1년중 몇 번째 주, 1~53

-- 시간 포맷
-- 시간: HH, HH12, HH24 
-- 분:MI 
-- 초:SS
SELECT TO_CHAR(SYSDATE, 'HH24:MI:SS') FROM DUAL;       -- 24시간단위 시:분:초
SELECT TO_CHAR(SYSDATE, 'HH12:MI:SS') FROM DUAL;       -- 12시간 단위 시:분:초
SELECT TO_CHAR(SYSDATE, 'HH:MI:SS') FROM DUAL;         -- 12시간 단위 시:분:초
SELECT TO_CHAR(SYSDATE, 'AM HH12:MI:SS') FROM DUAL;    -- 오전/오후
SELECT TO_CHAR(SYSDATE, 'PM HH12:MI:SS') FROM DUAL;    -- 오전/오후
SELECT TO_CHAR(SYSDATE, 'A.M. HH12:MI:SS') FROM DUAL;  -- 오전/오후
SELECT TO_CHAR(SYSDATE, 'P.M. HH12:MI:SS') FROM DUAL;  -- 오전/오후
SELECT TO_CHAR(SYSDATE, 'HH12:MI:SS AM') FROM DUAL;    -- 12시간 단위, 시:분:초