-- 날짜
-- SYSDATE : 현재 날짜
-- ADD_MONTH : 월을 다루는 함수

-- 오늘 날짜
SELECT SYSDATE FROM DUAL;
SELECT SYSDATE AS TODAY, ENAME FROM EMP;
-- 내일 날짜
SELECT SYSDATE + 1 AS TOMORROW FROM DUAL;
-- 어제 날짜
SELECT SYSDATE - 1 AS YESTERDAY FROM DUAL;
-- 일주일 후의 날짜
SELECT SYSDATE + 7 AS AFTERWEEK FROM DUAL;
----------------------------------------------------
-- ADD_MONTHS(날짜데이터, 더할 개월 수)

-- 다음 달(한 달 뒤)
SELECT ADD_MONTHS(SYSDATE, 1) AS NEXTMONTH FROM DUAL;
-- 지난 달(한 달 전)
SELECT ADD_MONTHS(SYSDATE, -1) AS LASTMONTH FROM DUAL;
-- 따옴표 붙여주기
SELECT ADD_MONTHS('20/08/11', -1) AS LASTMONTH FROM DUAL;
-------------------------------------------------------
-- 입사 10년차 사원 정보
SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 10 * 12) FROM EMP;
-- 입사 40년이 되는 날짜
SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 40 * 12) FROM EMP; 
-- 입사 40년 미만인 사원정보
SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 40 * 12)
    FROM EMP WHERE ADD_MONTHS(HIREDATE, 40 * 12) > SYSDATE;
-- 입사 40년 이상인 사원정보
SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 40 * 12)
    FROM EMP WHERE ADD_MONTHS(HIREDATE, 40 * 12) <= SYSDATE;
-- 입사 40년 이상인 사원정보
-- 입사 40년 이후 경과한 일수 : 날짜데이터 - 날짜데이터
SELECT EMPNO, ENAME, HIREDATE, ADD_MONTHS(HIREDATE, 40 * 12), TRUNC(SYSDATE - ADD_MONTHS(HIREDATE, 40 * 12)) AS PASSDATE
    FROM EMP WHERE ADD_MONTHS(HIREDATE, 40 * 12) <= SYSDATE;