-- 테이블에 데이터 삭제하기 : DELETE
-- DELETE [FROM] 테이블 이름 [WHERE 조건문]

CREATE TABLE DEPTX2 AS SELECT * FROM DEPTX;
SELECT * FROM DEPTX2;

DELETE FROM DEPTX2;
DELETE DEPTX2;

DELETE FROM DEPTX2 WHERE LOC LIKE '독도%';
SELECT * FROM EMPX;

-- [문제] 임시테이블 EMPX에서
-- 급여등급이 등급에 속하지 않는 모든 사원을 삭제
SELECT * FROM EMPX;
SELECT * FROM SALGRADE;

-- 급여등급이 등급 범위에 속하지 않는 모든 사원 정보
SELECT * FROM EMPX WHERE SAL < 700 OR SAL > 9999;
CREATE TABLE EMPX1 AS SELECT * FROM EMPX;
SELECT * FROM EMPX1 WHERE SAL < 700 OR SAL > 9999;

--급여등급 범위 내에 있는 사원 정보
SELECT E.* 
    FROM EMPX1 E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;
-- 삭제할 데이터를 검색
SELECT * FROM EMPX1 
    WHERE EMPNO NOT IN(SELECT E.EMPNO
        FROM EMPX1 E, SALGRADE S
        WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL);
-- 검색된 데이터를 삭제 (최선의 방법?)
DELETE FROM EMPX1 
    WHERE EMPNO NOT IN(SELECT E.EMPNO
        FROM EMPX1 E, SALGRADE S
        WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL);

SELECT * FROM EMPX1;

SELECT DISTINCT E.EMPNO, E.ENAME
    FROM EMPX E, SALGRADE S
    WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL;