-- 다중열 서브쿼리(MULTIPLE COLUMN SUBQUERY)
--검색 칼럼이 여러개인 경우, 복수열의 서브쿼리

-- 부서별 최고 급여액
SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO;

--다중열 서브쿼리
SELECT * 
    FROM EMP
    WHERE (DEPTNO, SAL) IN(SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO);
        -- 1개,    2개,            1개,   2개     짝 맞춰서
-- 개별적으로 쿼리
SELECT * 
    FROM EMP
    WHERE DEPTNO IN(SELECT DEPTNO FROM EMP GROUP BY DEPTNO)
    AND SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);
    
SELECT * FROM EMP WHERE SAL IN (SELECT MAX(SAL) FROM EMP GROUP BY DEPTNO);