--데이터 사전(Data Dictionary)
-- 접속한 사용자 정보

SELECT * FROM DICT WHERE TABLE_NAME LIKE 'USER_T%' ORDER BY 1;

-- 접속한 사용자 정보
DESC USER_TABLES;
SELECT * FROM USER_TABLES;

-- 사용자가 소유한 객체 정보
DESC ALL_TABLES;
SELECT * FROM ALL_TALBES;

SELECT * FROM ALL_TALBES WHERE OWNER = 'SCOTT';
SELECT * FROM ALL_TABLES WHERE OWNER = 'SOLUSER';
SELECT * FROM ALL_TALBES WHERE OWNER IN('SCOTT', 'SOLUSER');