-- 그룹함수: 다중행 함수
-- 데이터의 갯수
-- COUNT(COLUMN)

--전체 행의 갯수
SELECT COUNT(*) FROM EMP;
SELECT COUNT(EMPNO) FROM EMP;
SELECT COUNT(ENAME) FROM EMP;

-- 칼럼에 NULL이 있는 경우는 갯수에 포함되지 않음
SELECT COUNT(COMM) FROM EMP;
SELECT COUNT(COMM) FROM EMP WHERE COMM IS NOT NULL;

SELECT COUNT(COMM) FROM EMP WHERE COMM IS NULL;  -- 결과:0
SELECT COUNT(EMPNO) FROM EMP WHERE COMM IS NULL; -- 결과:8

